// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_bookmark

import (
	context "context"

	bookmark "github.com/HemlockPham7/golang-system-design/internal/service/bookmark"

	mock "github.com/stretchr/testify/mock"

	model "github.com/HemlockPham7/golang-system-design/internal/model"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateBookmark provides a mock function with given fields: ctx, description, url, userID
func (_m *Service) CreateBookmark(ctx context.Context, description string, url string, userID string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, description, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookmark")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.Bookmark, error)); ok {
		return rf(ctx, description, url, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Bookmark); ok {
		r0 = rf(ctx, description, url, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, description, url, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBookmark provides a mock function with given fields: ctx, userID, ID
func (_m *Service) DeleteBookmark(ctx context.Context, userID string, ID string) error {
	ret := _m.Called(ctx, userID, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookmarks provides a mock function with given fields: ctx, userID, page, limit
func (_m *Service) GetBookmarks(ctx context.Context, userID string, page int, limit int) (*bookmark.GetBookmarksResult, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarks")
	}

	var r0 *bookmark.GetBookmarksResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*bookmark.GetBookmarksResult, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *bookmark.GetBookmarksResult); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bookmark.GetBookmarksResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBookmark provides a mock function with given fields: ctx, description, url, userID, ID
func (_m *Service) UpdateBookmark(ctx context.Context, description string, url string, userID string, ID string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, description, url, userID, ID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookmark")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model.Bookmark, error)); ok {
		return rf(ctx, description, url, userID, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model.Bookmark); ok {
		r0 = rf(ctx, description, url, userID, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, description, url, userID, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
