upstream bookmark-service {
    server bookmark-service:8080;
}

upstream portal {
    server portal:3000;
}

limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://portal/;
    }

    location /api/bookmark-service/  {
        proxy_pass http://bookmark-service/;
        limit_req zone=api_limit burst=10 nodelay;
    }
}