// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockLink

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateShortenLink provides a mock function with given fields: ctx, url, expSecond
func (_m *Service) CreateShortenLink(ctx context.Context, url string, expSecond int64) (string, error) {
	ret := _m.Called(ctx, url, expSecond)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortenLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (string, error)); ok {
		return rf(ctx, url, expSecond)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = rf(ctx, url, expSecond)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, url, expSecond)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLinkFromCode provides a mock function with given fields: ctx, requestCode
func (_m *Service) GetLinkFromCode(ctx context.Context, requestCode string) (string, error) {
	ret := _m.Called(ctx, requestCode)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkFromCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, requestCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, requestCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
